config/routes.rb
Rails.application.routes.draw do
  root 'welcome#top'

  get 'diaries/*path' => 'welcome#top'

  namespace :api, { format: 'json' } do
    resources :diaries
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/api/diaries_controller.rb
class Api::DiariesController < Api::ApplicationController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]

  # GET /diaries
  # GET /diaries.json
  def index
      diaries = Diary.offset(params[:page].to_i*10).limit(10)
      size =  Diary.all.size

      render json: {diaries: diaries, size: size}
  end

  # GET /diaries/1
  # GET /diaries/1.json
  def show
    render json: @diary
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
    render json: @diary
  end

  # GET /diaries/1/edit
  def edit
    render json: @diary
  end

  # POST /diaries
  # POST /diaries.json
  def create
    @diary = Diary.new(diary_params)

    if @diary.save
      render :json, status: :created, location: @diary
    else
      render json: @diary.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /diaries/1
  # PATCH/PUT /diaries/1.json
  def update
    if @diary.update(diary_params)
      render :json, status: :ok, location: @diary
    else
      render json: @diary.errors, status: :unprocessable_entity
    end
  end

  # DELETE /diaries/1
  # DELETE /diaries/1.json
  def destroy
    @diary.destroy
    render json: (head :no_content)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_diary
    @diary = Diary.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def diary_params
    params.require(:diary).permit(:title, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/diaries/_form.html.haml
= form_for @diary do |f|
  - if @diary.errors.any?
    #error_explanation
      %h2= "#{pluralize(@diary.errors.count, "error")} prohibited this diary from being saved:"
      %ul
        - @diary.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/diaries/edit.html.haml
%h1 Editing diary

= render 'form'

= link_to 'Show', @diary
\|
= link_to 'Back', diaries_path

app/views/diaries/index.html.haml
%h1 Listing diaries

%table
  %thead
    %tr
      %th Title
      %th Body
      %th
      %th
      %th

  %tbody
    - @diaries.each do |diary|
      %tr
        %td= diary.title
        %td= diary.body
        %td= link_to 'Show', diary
        %td= link_to 'Edit', edit_diary_path(diary)
        %td= link_to 'Destroy', diary, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Diary', new_diary_path

app/views/diaries/new.html.haml
%h1 New diary

= render 'form'

= link_to 'Back', diaries_path

app/views/diaries/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @diary.title
%p
  %b Body:
  = @diary.body

= link_to 'Edit', edit_diary_path(@diary)
\|
= link_to 'Back', diaries_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ReactPractice
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/welcome/top.html.haml
= javascript_pack_tag 'top'